name: Deploy Website

on:
  push:
    branches:
      - main  # Adjust if your private repository uses a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Public Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Path to your built/static files in the private repository
          destination_repo: ioannalazaridou/ioannalazaridou.github.io
          destination_branch: main
